### ISSUE TITLE
Stylegan2 directions learning 

### ISSUE THREAD

**Issue by aomv** [5agado/data-science-learning#2]
Hi,

 On StyleGAN - Explore Directions.ipynb can you share exactly how did you learn the directions?
 Did you use the 18x512 latent or the 1x512?

Thank you

**Comment by 5agado** [comment]
At the time I used [GANSpace](https://github.com/harskish/ganspace). Very good approach, but there might be new projects tackling this task in a better or different way.

And directions are across all style layers (so 18, 16 or less, depending on your resolution)
