### ISSUE TITLE
Stylegan2 Pretained Model

### ISSUE THREAD

**Issue by geekmangnu** [5agado/data-science-learning#3]
Hi, stylegan2 pretrained models are limited in scope and could not found any deepfashion pretrained stylegan2 file then I found your informative medium post. Could you share your pretrained deepfashion dataset? It will be greatly appreciated. 
Thank you.

**Comment by 5agado** [comment]
I didn't use the deepfashion dataset for pretraining my model, but another dataset I personally curated which unfortunately I cannot share.
